# Debug Settings
env = HYPRLAND_TRACE,1
debug {
    disable_logs = false
}

$fileManager = thunar
$menu = zmenu
$cliPopup = floating-term

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Global Settings
general {
    gaps_in = 3
    gaps_out = 5,5,5,5
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}
master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    enable_anr_dialog = false
}

# Source other configs
source = config/*.conf
source = theme/*.conf

