exec-once = QT_QPA_PLATFORMTHEME=gtk3 qs -c noctalia-shell
# exec-once = dunst
# exec-once = hyprpaper -c "$HYPRPAPER_CONFIG"
# exec-once = wlsunset -S 05:30 -s 17:40
# exec-once = hypridle -c "$HYPRIDLE_CONFIG"
# exec-once = /home/eduardo/.config/waybar/launch.sh

